# Exclude commonly ignored directories
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
  ".venv"
]

line-length = 160
indent-width = 4

[lint]
select = ['ALL']
extend-select = ['ICN', 'TID', 'ASYNC', 'ANN', "A", "B", "C", "F"]
ignore = [
  "BLE001",

  "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107",
  "D205", "D400", "D401", "D402", "D404", "D414", "D415", "D417", "D418", "D419",

  "E501",
  "EM101",
  "FBT001",
  "G004",
  "INP001",
  "PLC0415",
  "PERF401", "PERF402",
  "RUF001",
  "TC002", "TC006", "TC001",
  "TRY003", "TRY300", "TRY301",
  "SIM108",
  "S311", "S608",
  "UP006",
  "W293", "W291",
  "C901",
  "PLR0915",
]

fixable = ["ALL"]

[lint.per-file-ignores]
"**/*_test.py" = ["T201", "S101", "PLR2004", "SLF001", "ARG001"]
"**/test/**/*.py" = ["T201", "S101", "PLR2004", "SLF001", "ARG001"]
"**/conftest.py" = ["T201", "S101", "PLR2004", "SLF001", "ARG001"]

[format]
quote-style = "double"

[lint.flake8-import-conventions.aliases]
numpy = "np"
scipy = "sp"
pyarrow = "pa"
typing = "t"
sqlalchemy = "sa"

[lint.flake8-import-conventions]
banned-from = ["typing"]
